### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by JiangDing1995** [LongJun123456/Tensorflow-Resnet-Image-Classification#2]
你好！感谢分享，代码下载之后我看data内并没有图片，请教一下：
1、意思是直接用我们自己的训练图片就可以了是吗，图片尺寸有没有要求；
2、需不需要自己制作标签，还是直接放在对应类别文件下就可以；
谢谢！

**Comment by LongJun123456** [comment]
1.尺寸有没有具体要求 会resize 但是尺寸最好在224*224左右
2.不用自己制作标签，直接放在对应类别文件下就行

**Comment by JiangDing1995** [comment]
十分感谢！

**Comment by JiangDing1995** [comment]
抱歉再次打扰您，请教下：
1、config.py文件中的decay_iters=50000,这个参数是什么意思呢，我在别的.py文件中并没有找到这个参数。
2、我用猫狗数据集做了个简单测试，得到xxx.jpg: catdog,是不是说哪一类在最前面就是这张图的预测类型？比如这个，预测的就是猫
还望指教！谢谢

**Comment by LongJun123456** [comment]
1.这个参数是之前调学习率用的
2.对的

**Comment by JiangDing1995** [comment]
谢谢！
